### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by changhui666** [ranahanocka/MeshCNN#140]
Traceback (most recent call last):
  File "train.py", line 30, in <module>
    model.optimize_parameters()
  File "/home/ch/MeshCNN-master/models/mesh_classifier.py", line 66, in optimize_parameters
    out = self.forward()
  File "/home/ch/MeshCNN-master/models/mesh_classifier.py", line 57, in forward
    out = self.net(self.edge_features, self.mesh)
  File "/usr/local/Anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/Anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/Anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ch/MeshCNN-master/models/networks.py", line 150, in forward
    x = getattr(self, 'pool{}'.format(i))(x, mesh)
  File "/home/ch/MeshCNN-master/models/layers/mesh_pool.py", line 21, in __call__
    return self.forward(fe, meshes)
  File "/home/ch/MeshCNN-master/models/layers/mesh_pool.py", line 34, in forward
    self.__pool_main(mesh_index)
  File "/home/ch/MeshCNN-master/models/layers/mesh_pool.py", line 53, in __pool_main
    self.__pool_edge(mesh, edge_id, mask, edge_groups)
  File "/home/ch/MeshCNN-master/models/layers/mesh_pool.py", line 61, in __pool_edge
    elif self.__clean_side(mesh, edge_id, mask, edge_groups, 0)\
  File "/home/ch/MeshCNN-master/models/layers/mesh_pool.py", line 79, in __clean_side
    self.__remove_triplete(mesh, mask, edge_groups, invalid_edges)
  File "/home/ch/MeshCNN-master/models/layers/mesh_pool.py", line 181, in __remove_triplete
    assert(len(vertex) == 1)
AssertionError

**Comment by littlezhang231** [comment]
Have you solved this problem and how did you solve it?Thank you for your reply
