### ISSUE TITLE
how to test on other obj files

### ISSUE THREAD

**Issue by shshwdr** [ranahanocka/MeshCNN#16]
Hi I think I'm confused about how to test my own test case. run those commands(human segmentation related) works fine for me, but if I want to segment some other obj file, what should I do? I tried to put my obj file in test but that doesn't seem to work, it ask me to have seg files.
Thanks a lot and really appreciate your code.

**Comment by ranahanocka** [comment]
Hi @shshwdr ,

Yes I didn't include this functionality, I probably should have.

Currently, the ground-truth seg files are used to calculate the test accuracy. So, I think the easiest hack to just get the code to work is to create some dummy seg files which are all zeros or something -- (just ignore the printed accuracy), and everything should run fine. Please check the [segmentation wiki](https://github.com/ranahanocka/MeshCNN/wiki/Segmentation) for more info on these files.

-Rana

**Comment by shshwdr** [comment]
I added two all zerod files in seg and sseg, then I got this error when I run test:
Running Test
loaded mean / std from cache
loading the model from ./checkpoints\human_seg\latest_net.pth
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    run_test()
  File "test.py", line 16, in run_test
    for i, data in enumerate(dataset):
  File "C:\Users\si.chen\Desktop\MeshCNN-master\data\__init__.py", line 33, in __iter__
    for i, data in enumerate(self.dataloader):
  File "C:\Users\si.chen\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "C:\Users\si.chen\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "C:\Users\si.chen\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\si.chen\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\si.chen\Desktop\MeshCNN-master\data\segmentation_data.py", line 33, in __getitem__
    label = pad(label, self.opt.ninput_edges, val=-1, dim=0)
  File "C:\Users\si.chen\Desktop\MeshCNN-master\util\util.py", line 22, in pad
    return np.pad(input_arr, pad_width=npad, mode='constant', constant_values=val)
  File "<__array_function__ internals>", line 6, in pad
  File "C:\Users\si.chen\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\arraypad.py", line 793, in pad
    pad_width = _as_pairs(pad_width, array.ndim, as_index=True)
  File "C:\Users\si.chen\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\arraypad.py", line 560, in _as_pairs
    raise ValueError("index can't contain negative values")
ValueError: index can't contain negative values

**Comment by shshwdr** [comment]
I tried to find a object with 2259 edges and my setting are:
--ninput_edges 2259 \
--pool_res 1800 1350 600 \
the seg and sseg files both contain 2259 rows.

**Comment by yjh720** [comment]
> I tried to find a object with 2259 edges and set the ninput_edges to 2259, pool_res to 1800 1350 600
> and get the result.
> But the result is quite not as I expected since it segment in weird position. Is the settings I put in correct? should I add both seg and sseg file? is there anything I can do to improve it? or it's just I need to train more human models? thanks.

Hi @shshwdr,
I'm doing some similar thing. However, I'm not able to segment my objs. The results is always the human segmentation even if I change the obj file(without touching seg files). Do you mind teaching me how to doing your own segmentation?

**Comment by ranahanocka** [comment]
> I tried to find a object with 2259 edges and set the ninput_edges to 2259, pool_res to 1800 1350 600
> and get the result.
> But the result is quite not as I expected since it segment in weird position. Is the settings I put in correct? should I add both seg and sseg file? is there anything I can do to improve it? or it's just I need to train more human models? thanks.

If you are using my pre-trained network, then you should not change `ninput_edges` parameter, then it will not work. Please use the default for segmentation (for humans it is `--ninput_edges 2280`) and re-run. The test requires both seg and sseg (unless you want to modify the accuracy computation). I think you can just comment out [this line](https://github.com/ranahanocka/MeshCNN/blob/cf93099bb1de4b5fbd9c18e6241af298b839af06/models/mesh_classifier.py#L115) and then maybe you won't need the seg / sseg files anymore

**Comment by zhoujinhai** [comment]
> Hi I think I'm confused about how to test my own test case. run those commands(human segmentation related) works fine for me, but if I want to segment some other obj file, what should I do? I tried to put my obj file in test but that doesn't seem to work, it ask me to have seg files.
> I don't need to test the result of the segmentation, just want to segment with trained data.
> Thanks a lot and really appreciate your code.

Do you have running  test  success without ground-truth seg files?

**Comment by Eisorak** [comment]
Hi @shshwdr 

were you able to perform a test without field truth segmentation files?
