### ISSUE TITLE
Some error I don't quite understand

### ISSUE THREAD

**Issue by Pavelevivan** [ranahanocka/MeshCNN#83]
I tried to run your model on my objects for classification task using the same settings as for shrec dataset. One change is  my objects have 1000 faces and I set up ninput_edges = 1500
Traceback (most recent call last):
  File "train.py", line 30, in <module>
    model.optimize_parameters()
  File "/content/MeshCNN/models/mesh_classifier.py", line 66, in optimize_parameters
    out = self.forward()
  File "/content/MeshCNN/models/mesh_classifier.py", line 57, in forward
    out = self.net(self.edge_features, self.mesh)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/MeshCNN/models/networks.py", line 150, in forward
    x = getattr(self, 'pool{}'.format(i))(x, mesh)
  File "/content/MeshCNN/models/layers/mesh_pool.py", line 21, in __call__
    return self.forward(fe, meshes)
  File "/content/MeshCNN/models/layers/mesh_pool.py", line 34, in forward
    self.__pool_main(mesh_index)
  File "/content/MeshCNN/models/layers/mesh_pool.py", line 53, in __pool_main
    self.__pool_edge(mesh, edge_id, mask, edge_groups)
  File "/content/MeshCNN/models/layers/mesh_pool.py", line 61, in __pool_edge
    elif self.__clean_side(mesh, edge_id, mask, edge_groups, 0)\
  File "/content/MeshCNN/models/layers/mesh_pool.py", line 79, in __clean_side
    self.__remove_triplete(mesh, mask, edge_groups, invalid_edges)
  File "/content/MeshCNN/models/layers/mesh_pool.py", line 181, in __remove_triplete
    assert(len(vertex) == 1)
AssertionError

**Comment by ranahanocka** [comment]
Hi @Pavelevivan ,

I think your mesh is non-manifold. Did you check in meshlab?
![image](https://user-images.githubusercontent.com/14359648/84590455-7823b480-ae3f-11ea-898e-cb98dc5947c5.png)

**Comment by Pavelevivan** [comment]
Yes, you are right. Thank you!
